### ISSUE TITLE
GitHub repository settings misconfigured: usdot-fhwa-stol/voices-common-interface develop branch

### ISSUE THREAD

**Issue by codygarver** [usdot-fhwa-stol/devops#126]
### Component

Infrastructure

### Specifics

- [ ] CircleCI
- [ ] Docker or Docker Hub
- [ ] Doxygen
- [ ] GitHub Actions
- [X] GitHub branch or repo
- [ ] Sonar

### What happened?

The following [usdot-fhwa-stol/voices-common-interface settings](https://github.com/usdot-fhwa-stol/voices-common-interface/settings) are misconfigured:
- [ ] "Branch protection rules" disabled!

**Comment by grayson-wood** [comment]
**Deviations and Issues with Aligning with carma-platform repo settings**

Unable to add usdot-fhwa-stol/administration group to master & develop branch push to matching branches ruleset.
Master branch rules do not apply to any branches. (No master branch present)
Did not make release/* branch rules due to no release branches.

**Summary of current progress**

Added and aligned master branch protection rules with carma-platform/master.
Added and aligned develop branch protection rules with carma-platform/develop.
Allowed force pushes on develop branch, in line with carma-platform/develop.

**Comment by paulbourelly999** [comment]
Added administration team to repo and to push privileges for master and develop
